In [1]:
import pandas as pd

In [2]:
a = [4, 5, 2, 98]
b = [6, 34, 76, 1]
c = [98, 43, 23, 4]

In [3]:
arla = pd.DataFrame({'a': a,
                   'b' : b,
                   'c' : c})

In [4]:
type(arla)

pandas.DataFrame

In [5]:
arla

    a   b   c
0   4   6  98
1   5  34  43
2   2  76  23
3  98   1   4

In [8]:
arla["row_mean"] = arla.mean(axis=1)

In [9]:
arla

    a   b   c   row_mean
0   4   6  98  36.000000
1   5  34  43  27.333333
2   2  76  23  33.666667
3  98   1   4  34.333333

In [ ]:
#kortlink.dk/2thxg

In [14]:
df = pd.read_csv('/work/ExPsyLing_E2026/Stroop-raw-over-the-years.csv')

In [15]:
df = pd.read_csv('/work/ExPsyLing_E2026/Stroop-raw-over-the-years.csv')

In [16]:
df

     Reading_NoInt  Naming_Int  Naming_NoInt  Reading_Int  Year
0             4.16        6.76          4.45         4.65  2015
1             4.35        7.73          4.78         4.46  2015
2             3.60        7.00          4.00         3.50  2015
3             3.90        9.03          4.60         6.30  2015
4             4.22        9.98          6.83         6.24  2015
..             ...         ...           ...          ...   ...
200           4.77       10.00          5.66         6.24  2025
201           4.61       12.80          6.87         9.55  2025
202           4.79       10.72          5.64         7.25  2025
203           4.41        8.87          6.70         6.70  2025
204           5.50        9.80          6.20        21.70  2025

[205 rows x 5 columns]