In [20]:
import pandas as pd

In [21]:
raw = pd.read_csv('/work/ExPsyLing_E2026/Experiment_with_Ethan/combined_data.csv')

HUSK at indsætte /work/ foran stien

In [22]:
#raw.head(50)

In [22]:
list(raw) #how to see the colum names

['participant_id',
 'component_num',
 'url',
 'meta',
 'sender',
 'sender_type',
 'sender_id',
 'ended_on',
 'duration',
 'time_run',
 'time_render',
 'time_show',
 'time_end',
 'time_commit',
 'timestamp',
 'time_switch',
 'response',
 'response_action',
 'prime',
 'target',
 'condition',
 'soa_condition',
 'congruence',
 'correct_response',
 'correctResponse',
 'correct']

In [23]:
cols = ['participant_id', 
        'sender', 
        'duration', 
        'prime',
        'target',
        'response', 
        'condition', 
        'soa_condition', 
        'congruence', 
        'correct_response', 
        'correct', ]
#cols is short for colums
    #making a list of all the stuff we need

In [24]:
df = raw[cols]
#df is short for dataframe

In [25]:
df = df[df['sender'] == 'target'] 
#the two == means "is equal to". Så vi fjerner alle de colunner, hvor det ikke er "target" der er afsender. Så vi kun har det vi faktisk skal bruge.

In [51]:
df

,participant_id,sender,duration,prime,target,response,condition,soa_condition,congruence,correct_response,correct
0,51,Wecome1,499.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,51,Wecome2,499.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,51,Wecome3,499.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,51,Instructions1,9061.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,51,Instructions 1a,2279.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
15632,69,Short Loop,85426.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15633,69,Break,868.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15634,69,Short Sequence,86318.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15635,69,Experiment Sequence,183618.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15636,69,root,216385.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df['sender'].unique()
#tjekker om der er andet end "target" som "sender"

<StringArray>
['target']
Length: 1, dtype: str

In [27]:
df = df[df['condition'] != 'practice'] #finds everything that is NOT practice
df = df.drop(columns = ['sender']) #fjerner kolonnen med 'sender'

In [28]:
df

,participant_id,duration,prime,target,response,condition,soa_condition,congruence,correct_response,correct
40,51,520.14,roof,PIANO,m,Inc_Synth_Synth,long,incongruent,m,True
47,51,640.66,sheep,BULL,n,Inc_Nat_Nat,long,incongruent,m,False
54,51,597.74,fort,GOAT,n,Inc_Synth_Nat,long,incongruent,n,True
61,51,495.68,pear,PEAR,n,Con_Nat,long,congruent,n,True
68,51,556.86,olive,MOTOR,m,Inc_Nat_Synth,long,incongruent,m,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,belt,BELT,m,Con_Synth,short,congruent,m,True
15612,69,580.20,daisy,DAISY,n,Con_Nat,short,congruent,n,True
15618,69,577.90,peach,SHED,m,Inc_Nat_Synth,short,incongruent,m,True
15624,69,661.10,rake,HUSKY,n,Inc_Synth_Nat,short,incongruent,n,True
15630,69,709.20,fern,PETAL,n,Inc_Nat_Nat,short,incongruent,n,True

In [29]:
df.loc[df['target'] == 'BULL', 'correct_response'] = 'n'

In [30]:
df

,participant_id,duration,prime,target,response,condition,soa_condition,congruence,correct_response,correct
40,51,520.14,roof,PIANO,m,Inc_Synth_Synth,long,incongruent,m,True
47,51,640.66,sheep,BULL,n,Inc_Nat_Nat,long,incongruent,n,False
54,51,597.74,fort,GOAT,n,Inc_Synth_Nat,long,incongruent,n,True
61,51,495.68,pear,PEAR,n,Con_Nat,long,congruent,n,True
68,51,556.86,olive,MOTOR,m,Inc_Nat_Synth,long,incongruent,m,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,belt,BELT,m,Con_Synth,short,congruent,m,True
15612,69,580.20,daisy,DAISY,n,Con_Nat,short,congruent,n,True
15618,69,577.90,peach,SHED,m,Inc_Nat_Synth,short,incongruent,m,True
15624,69,661.10,rake,HUSKY,n,Inc_Synth_Nat,short,incongruent,n,True
15630,69,709.20,fern,PETAL,n,Inc_Nat_Nat,short,incongruent,n,True

In [18]:
#df['accuracy'] = df['response'] == df['correct_response'] #still working on fixing the "bull" mistake
#we made a new column called accuracy to fix it

In [31]:
df

,participant_id,duration,prime,target,response,condition,soa_condition,congruence,correct_response,correct
40,51,520.14,roof,PIANO,m,Inc_Synth_Synth,long,incongruent,m,True
47,51,640.66,sheep,BULL,n,Inc_Nat_Nat,long,incongruent,n,False
54,51,597.74,fort,GOAT,n,Inc_Synth_Nat,long,incongruent,n,True
61,51,495.68,pear,PEAR,n,Con_Nat,long,congruent,n,True
68,51,556.86,olive,MOTOR,m,Inc_Nat_Synth,long,incongruent,m,True
...,...,...,...,...,...,...,...,...,...,...
15606,69,699.20,belt,BELT,m,Con_Synth,short,congruent,m,True
15612,69,580.20,daisy,DAISY,n,Con_Nat,short,congruent,n,True
15618,69,577.90,peach,SHED,m,Inc_Nat_Synth,short,incongruent,m,True
15624,69,661.10,rake,HUSKY,n,Inc_Synth_Nat,short,incongruent,n,True
15630,69,709.20,fern,PETAL,n,Inc_Nat_Nat,short,incongruent,n,True

In [32]:
df_grouped = df.groupby(['soa_condition', 'congruence']).mean(['duration'])
#ethan will fix the error later....

ValueError: numeric_only accepts only Boolean values

In [ ]:
#run when Ethan has fixed the above error
#df_grouped = df_grouped.reset_index()
#df_grouped

In [34]:
%pip install seaborn

Collecting seaborn

  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/conda/lib/python3.13/site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in /opt/conda/lib/python3.13/site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/conda/lib/python3.13/site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: pillow>=9 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)

Installing collected packages: seaborn

Successfully installed seaborn-0.13.2

Note: you may need to restart the kernel to use updated packages.

In [36]:
import seaborn as sns

In [ ]:
ax = sns.barplot(data = df_grouped, x = 'congruence', y = 'duration', hue = 'soa_condition')